name: Build RandomBMPreset DLL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download BakkesMod SDK
      run: git clone https://github.com/bakkesmodorg/BakkesModSDK.git bakkesmod

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Build solution
      run: msbuild RandomBMPreset.sln

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: RandomBMPreset-DLL
        path: |
          **/Release/*.dll
